#!/usr/bin/env python
import asyncio
import socketio
import sys

sio = socketio.Client()

@sio.event
def translation(text):
    print(text)
    sio.disconnect()
    exit(0)

if __name__ == '__main__':
    if (len(sys.argv) != 2):
        print("Usage: {} \"quoted text in French\"".format(sys.argv[0]))
        exit(1)
    text = sys.argv[1]
    try:
        sio.connect('http://localhost:8080', auth={'text': text}, transports=['polling'])
    except socketio.exceptions.ConnectionError:
        pass
