#!/usr/bin/env python
import http.client
import sys

if __name__ == '__main__':
    if (len(sys.argv) != 2):
        print("Usage: {} \"quoted text in Chinese\"".format(sys.argv[0]))
        exit(1)
    text = sys.argv[1]

    conn = http.client.HTTPConnection("localhost", 8080)
    headers = {'Content-type': 'text'}

    conn.request('POST', '/', text.encode('utf-8'), headers)

    response = conn.getresponse()
    print(response.read().decode())

